connectionStrings: 
    MicroservicesClientConnectionString: Data Source=.;Initial Catalog=LibraryRelease;Persist Security Info=True;User ID=galaxy;Password=Password123  
JwtSettings: 
    Key: nskljgfdgokwernglsndgjknsñdjgnskjdfgnlkjsdnfskdjgsdjfkg
    Issuer: https://localhost:44323/
    Audience: Microservices.ConfigServer.ClientRelease
    MinuteExpiration: 10
  