WebApiGatewaySettings:
    Secret: THIS_IS_A_RANDOM_SECRET_2e7a1e80-16ee-4e52-b5c6-5e8892453459
    AllowedChatOrigins:
        - https://localhost:44300
        - https://localhost:44398
ReRoutes: 
    -    
        DownstreamPathTemplate: /api/Products/{everything}
        DownstreamScheme: https
        UpstreamPathTemplate: /api/Products/{everything}
        ServiceName: Microservices.Demo.Product.API
        UpstreamHttpMethod: 
            - Get
        FileCacheOptions: 
            TtlSeconds: 15
        AuthenticationOptions:
            AuthenticationProviderKey: ApiSecurityAuthenticationScheme
            AllowedScopes: 
                -
        RouteClaimsRequirement:
            userType: SALESMAN      
        DangerousAcceptAnyServerCertificateValidator: true    
GlobalConfiguration:
    RequestIdKey: OcRequestId
    AdministrationPath: /administration
    UseServiceDiscovery: true
    ServiceDiscoveryProvider:
        Type: Eureka
        Host: localhost
        Port: 8761