WebApiGatewaySettings:
    Secret: THIS_IS_A_RANDOM_SECRET_2e7a1e80-16ee-4e52-b5c6-5e8892453459
    AllowedChatOrigins:
        - https://localhost:44300
        - https://localhost:44398
GlobalConfiguration:
    RequestIdKey: OcRequestId
    AdministrationPath: /administration
    UseServiceDiscovery: true
    ServiceDiscoveryProvider:
        Type: Eureka
        Host: localhost
        Port: 8761